### ISSUE TITLE
[Feature request]: Consider using different branches or tags for to track particular released versions. 

### ISSUE THREAD

**Issue by tvalentyn** [liran-funaro/objsize#4]
Looks like this repository only has a master branch.
Typically,  open-source projects hosted on Github use tags or branches that allow to easily look up the version of the codebase as of a particular release. This also allows one to check the diff between particular versions.

Thanks a lot for implementing this library!

**Comment by liran-funaro** [comment]
Thanks for the suggestion. I created tags for all previous versions and will continue doing so for future versions.

**Comment by tvalentyn** [comment]
Thank you for a quick response! I am working on an Apache project and unfortunately after taking a closer look, it might be difficult for us to use objsize since it is licensed under GPL v3, which doesn't play well with ASF guidelines: https://apache.org/legal/resolved.html#optional.

We were really looking forward to using objsize...

**Comment by liran-funaro** [comment]
This is already requested in #5. I'll consider changing the license.

**Comment by tvalentyn** [comment]
off-topic question: would you anticipate any breaking api changes before the version 1.0 is released ?

**Comment by liran-funaro** [comment]
The current API is stable and should remain for version 1.0.
My plan for version 1.0 is to add a "higher level" API that allows less complicated handling of non-trivial objects (e.g., `torch.Tensor`).
