### ISSUE TITLE
Swap to or dual license with ASF compatible license?

### ISSUE THREAD

**Issue by lukecwik** [liran-funaro/objsize#5]
Would you consider dual licensing or swapping to use an [ASF compatible license](https://apache.org/legal/resolved.html#category-a)?

I was looking to include this dependency within another ASF project (Apache Beam) but was unable to due to [ASF license policy preventing GPL v3](https://apache.org/legal/resolved.html#category-x) from being included.

**Comment by liran-funaro** [comment]
I'll have to take a look at these ASF-compatible licenses. I will update you next week.

**Comment by lukecwik** [comment]
Thanks.

**Comment by lukecwik** [comment]
Also, if you do decide on swapping licenses, would you release an artifact with the new license?

**Comment by liran-funaro** [comment]
@lukecwik @tvalentyn I updated the license to BSD-3 to allow apache/beam and other projects to include this package as part of their software bundle.
I released a new artifact as version 0.5.2: https://pypi.org/project/objsize/0.5.2/.

**Comment by tvalentyn** [comment]
Thank you so much!

**Comment by lukecwik** [comment]
Swapped to 0.5.2 within Apache Beam with https://github.com/apache/beam/pull/23211
