### ISSUE TITLE
objsize fails to size weakref proxy raising ReferenceError

### ISSUE THREAD

**Issue by lukecwik** [liran-funaro/objsize#6]
I get the following error:
```
  in test_size_of_weakref
    print(objsize.get_deep_size(oref))
  File ".../python/.eggs/objsize-0.5.2-py3.8.egg/objsize.py", line 235, in get_deep_size
    return sum(map(get_size_func, it))
  File ".../python/.eggs/objsize-0.5.2-py3.8.egg/objsize.py", line 91, in traverse_bfs
    objs = {o_id: o for o_id, o in objs if o_id not in marked and filter_func(o)}
  File ".../python/.eggs/objsize-0.5.2-py3.8.egg/objsize.py", line 91, in <dictcomp>
    objs = {o_id: o for o_id, o in objs if o_id not in marked and filter_func(o)}
  File ".../python/.eggs/objsize-0.5.2-py3.8.egg/objsize.py", line 43, in default_object_filter
    return not isinstance(o, type)
ReferenceError: weakly-referenced object no longer exists
```

when running the following test:
```python
import unittest
import objsize
import weakref
import threading

class Foo(list):
  pass

class WeakRefTest(unittest.TestCase):
  def test_size_of_weakref(self):
    wait_event = threading.Event()
    o = Foo("SuperDuper")
    oref = weakref.proxy(o, lambda value: wait_event.set())
    del o
    wait_event.wait()
    objsize.get_deep_size(oref)
```

**Comment by liran-funaro** [comment]
Thanks for catching this!

It should be noted that proxy/ref referenced objects are not tracked by the GC, so `gc.get_referents(oref)` does not return them. Thus, the referenced object's size is not counted.

I'll try to address the error and the `weakref` size calculation in the following release.

For now, if you want to avoid the error without accounting for the referenced object, you can call `objsize` as follows:
```python
objsize.get_deep_size(oref, filter_func=lambda o: not isinstance(o, (*weakref.ProxyTypes, type)))
```
This will return `0`.

If you want to account for the size of the referenced object, you can do so as follows:
```python
def get_referents(*objs):
    yield from gc.get_referents(*objs)
    
    for o in objs:
        if isinstance(o, weakref.ProxyTypes):
            try:
                yield o.__repr__.__self__
            except ReferenceError:
                pass
            
def filter_objct(o):
    return isinstance(o, weakref.ProxyTypes) or not isinstance(o, (type, types.FunctionType, types.LambdaType))
    
print(objsize.get_deep_size(oref, filter_func=filter_objct, get_referents_func=get_referents))
```

* Note that I added a filter to ignore function/lambda types so the proxy's callback will not be counted.
* `o.__repr__.__self__` retrieves the referenced object from the proxy. `weakref` doesn't support retrieving the referenced object, so I used this hack.

**Comment by lukecwik** [comment]
In Apache Beam's use-case for sizing elements in the cache we would rather not count the size of the weak references since the object will go out of reference as soon as the user stops using it.

**Comment by liran-funaro** [comment]
OK. Please notice I updated my response.
In the next release, I'll use the `type()` method instead of `isinstance()` so you'll not get an exception.

**Comment by lukecwik** [comment]
Does weakref remove the callback after it is invoked?

If not then it seems like accounting for the callback makes the most sense and your earlier suggestion of `objsize.get_deep_size(oref, filter_func=lambda o: type(o) is not type)` seemed to make the most sense for Apache Beam's use case.

**Comment by liran-funaro** [comment]
But if the callback is a shared function, then it should not be included in the calculation anyway.

**Comment by lukecwik** [comment]
In Apache Beam's usecase it is not possible to know whether the callback is specific to the object or shared across multiple objects. Accounting for shared objects is quite difficult in general or expensive from a performance point of view. For the Apache Beam use case both over counting (leads to cache being filled with less stuff then it could have been which increases amount of cache misses) and under counting (leads to OOMs) have bad outcomes but the former is less bad.

**Comment by liran-funaro** [comment]
With the same logic, I argue that `type` objects should also be included since python supports generating types on the fly.
Is this relevant to your use case?

**Comment by lukecwik** [comment]
`type`s and `module`s are very likely to be shared. They also aren't freed without some kind of user action, (e.g. the value is out of the cache and deleted).

**Comment by liran-funaro** [comment]
The latest release ([0.6.0](https://pypi.org/project/objsize/0.6.0/)) addresses this issue.
* It does not fail with `ReferenceError`
* It has an option to include functions/lambdas 

I also address these issues in the readme and in the unit tests.

You should use it as follows:
```python
def get_weakref_referents(*objs):
    yield from gc.get_referents(*objs)
    
    for o in objs:
        if type(o) in weakref.ProxyTypes:
            try:
                # A hack to retrieve the referenced object from the proxy (not supported by `weakref`)
                yield o.__repr__.__self__
            except ReferenceError:
                pass

# The default filter_func in version 0.6.0 is `objsize.shared_object_or_function_filter`,
# but here we use the version that does not filter functions
objsize.get_deep_size(oref, get_referents_func=get_referents, filter_func=objsize.shared_object_filter)
```

**Comment by lukecwik** [comment]
Thanks.

Through this discussion I was able to update my usage of objsize to work well for my usecase.

**Comment by liran-funaro** [comment]
Great. Just a quick note.

My initial suggestion (using `type(o) == type`) does not work.
You must use `isinstance(o, type)` for classes.
For that, I introduced `objsize.safe_is_instance()`. It works the same as `isinstance()` but catches `ReferenceError`.

Regarding including functions/lamdas sizes, it is only possible since version 0.6.0.
